In [2]:
#1.Создать вектор (одномерный массив) размера 100, заполненный нулями
import numpy
n = numpy.zeros(100)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [3]:
#2.Создать вектор размера 100, заполненный единицами
m = numpy.ones(100)
print(m)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [4]:
#3.Создать вектор размера 100, заполненный числом 3
q = numpy.full(100, 3)
print(q)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [8]:
#4. Поменять 2 строки в матрице
S = numpy.arange(16).reshape(4,4)
print(S)
S[[0,1]] = S[[1,0]]
print('После изменения:')
print(S)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
После изменения:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
#5. Создать вектор со значениями от 10 до 100
z = numpy.arange(10,101)
print(z)


[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [6]:
#6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16
S= numpy.arange(16).reshape(4,4)
print(S)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:

#7. Создать 3x3 единичную матрицу
p = numpy.eye(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#8. Создать массив 3x3x3 со случайными значениями
n = numpy.random.random((3,3,3))
print(n)

[[[0.55477315 0.75536632 0.98357071]
  [0.07213609 0.67836125 0.5128751 ]
  [0.32414006 0.45484659 0.90881887]]

 [[0.23168823 0.61651116 0.39386686]
  [0.66745898 0.74360024 0.22833827]
  [0.53583671 0.26335083 0.29873519]]

 [[0.13548935 0.64841814 0.36366306]
  [0.39538322 0.92849547 0.40697557]
  [0.13700005 0.46974171 0.85522913]]]


In [9]:

#9. Создать массив 10x10 со случайными значениями, найти минимум и максимум
M = numpy.random.random((10,10))
Mmin, Mmax = M.min(), M.max()
print(Mmin, Mmax)

0.019211014146094274 0.9995358364962605


In [10]:
#10. Создать случайный вектор размера 30 и найти среднее значение всех элементов
q = numpy.random.random(30)
m = q.mean()
print(m)

0.601326404693568


In [11]:
#11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(numpy.unravel_index(100, (6,7,8)))


(1, 5, 4)


In [12]:

#12. Перемножить матрицы 5x3 и 3x2
n = numpy.dot(numpy.ones((5,3)), numpy.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [13]:
#13. Дан массив, поменять знак у элементов, значения которых между 3 и 8
N = numpy.arange(15)
N[(3 < N) & (N <= 8)] *= -1
print(N)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [14]:
#14. Создать 5x5 матрицу со значениями в строках от 0 до 4
M = numpy.zeros((5,5))
M += numpy.arange(5)
print(M)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [15]:
#15. Отнять среднее из каждой строки в матрице
X = numpy.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)


[[0.06779088 0.38813015 0.06587245 0.50674715 0.63792406 0.00496164
  0.20915348 0.82335    0.70290301 0.28213183]
 [0.73081714 0.79219785 0.42025693 0.96915219 0.66352956 0.44377503
  0.7628455  0.54278332 0.18001784 0.41562773]
 [0.50249356 0.10088274 0.67592042 0.26658886 0.76056641 0.59413556
  0.56380601 0.93636575 0.61448198 0.9005148 ]
 [0.43966966 0.54909225 0.09091351 0.914847   0.03530026 0.19088792
  0.85956418 0.621736   0.12616892 0.89017166]
 [0.34637117 0.40146813 0.11330885 0.74729852 0.96392733 0.5357915
  0.40332051 0.54051103 0.07312129 0.24109628]]
[[-0.30110559  0.01923368 -0.30302401  0.13785068  0.2690276  -0.36393483
  -0.15974299  0.45445354  0.33400654 -0.08676463]
 [ 0.13871683  0.20009754 -0.17184338  0.37705188  0.07142925 -0.14832528
   0.17074519 -0.04931699 -0.41208247 -0.17647258]
 [-0.08908205 -0.49069286  0.08434482 -0.32498675  0.1689908   0.00255995
  -0.0277696   0.34479014  0.02290637  0.30893919]
 [-0.03216548  0.07725711 -0.38092163  0.44301186 